services:
  - type: web
    name: cirvio
    env: node
    rootDir: cirvio-backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_ORIGIN
        value: "*"
      - key: AUTO_APPROVE_LISTINGS
        value: "false"
      - key: ADMIN_EMAIL
        value: alishafaq782@gmail.com
